api_key: fakekey
galaxy_instance: http://localhost:8080
install_resolver_dependencies: true
install_tool_dependencies: false
tools:

- name: fastqc
  owner: devteam
  tool_panel_section_label: 'FASTQ Quality Control'
  tool_shed_url: https://toolshed.g2.bx.psu.edu

- name: bowtie2
  owner: devteam
  tool_panel_section_label: 'Mapping'
  tool_shed_url: https://toolshed.g2.bx.psu.edu

- name: bedtools
  owner: iuc
  tool_panel_section_label: 'Bedtools'
  tool_shed_url: https://toolshed.g2.bx.psu.edu

- name: text_processing
  owner: bgruening
  tool_panel_section_label: 'Text Manipulation'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
